//
//  StringConstants.swift
//  fotofolio2pto
//
//  Created by Kryštof Příhoda on 11.03.2025.
//

public let czechCities: [String] = [
    "Abertamy", "Adamov", "Aš", "Bakov nad Jizerou", "Bavorov", "Bechyně",
    "Bělá nad Radbuzou", "Bělá pod Bezdězem", "Benátky nad Jizerou", "Benešov",
    "Benešov nad Ploučnicí", "Benátky nad Jizerou", "Beroun", "Bezdružice",
    "Bílina", "Bílovec", "Blansko", "Blatná", "Blovice", "Bohumín",
    "Bohušovice nad Ohří", "Bojkovice", "Bor", "Borohrádek", "Boskovice",
    "Boží Dar", "Brandýs nad Labem-Stará Boleslav", "Brandýs nad Orlicí",
    "Brno", "Broumov", "Brtnice", "Brumov-Bylnice", "Bruntál", "Brušperk",
    "Břeclav", "Březnice", "Březová", "Březová nad Svitavou", "Břidličná",
    "Bučovice", "Budyně nad Ohří", "Budišov nad Budišovkou", "Bystřice",
    "Bystřice nad Pernštejnem", "Bystřice pod Hostýnem", "Bystré", "Bzenec",
    "Cvikov", "Čáslav", "Čelákovice", "Černošice", "Černovice",
    "Červený Kostelec", "Česká Kamenice", "Česká Lípa", "Česká Skalice",
    "České Budějovice", "České Velenice", "Český Brod", "Český Dub",
    "Český Krumlov", "Český Těšín", "Chabařovice", "Chlumec",
    "Chlumec nad Cidlinou", "Choceň", "Chodov", "Chomutov", "Chotěboř",
    "Chotěmice", "Chotěšov", "Chropyně", "Chrast", "Chrastava", "Chrudim",
    "Chýnov", "Dačice", "Dašice", "Desná", "Dobrovice", "Dobruška", "Dobřany",
    "Dobřichovice", "Dobříš", "Doksy", "Dolní Benešov", "Dolní Bousov",
    "Dolní Kounice", "Domažlice", "Dubá", "Dubí", "Dubňany", "Duchcov",
    "Dvůr Králové nad Labem", "Františkovy Lázně", "Frýdek-Místek", "Frýdlant",
    "Frýdlant nad Ostravicí", "Fulnek", "Golčův Jeníkov", "Habartov", "Habry",
    "Hanušovice", "Harrachov", "Hartmanice", "Havířov", "Havlíčkův Brod",
    "Hejnice", "Heřmanův Městec", "Hlinsko", "Hluboká nad Vltavou", "Hlučín",
    "Hodkovice nad Mohelkou", "Hodonín", "Holešov", "Holice", "Holýšov",
    "Hora Svaté Kateřiny", "Horažďovice", "Horní Benešov", "Horní Blatná",
    "Horní Bříza", "Horní Cerekev", "Horní Jelení", "Horní Jiřetín",
    "Horní Planá", "Horní Slavkov", "Horšovský Týn", "Hořice", "Hořovice",
    "Hostinné", "Hostivice", "Hostomice", "Hostouň", "Hradec Králové",
    "Hradec nad Moravicí", "Hrádek", "Hrádek nad Nisou", "Hranice",
    "Hranice (okres Cheb)", "Hronov", "Hrotovice", "Hrušovany nad Jevišovkou",
    "Hulín", "Humpolec", "Hustopeče", "Ivančice", "Ivanovice na Hané",
    "Jablonec nad Jizerou", "Jablonec nad Nisou", "Jablonné nad Orlicí",
    "Jablonné v Podještědí", "Jáchymov", "Janov", "Janovice nad Úhlavou",
    "Janské Lázně", "Jaroměř", "Jaroměřice nad Rokytnou", "Javorník", "Jemnice",
    "Jesenice", "Jeseník", "Jevíčko", "Jičín", "Jihlava", "Jilemnice", "Jílové",
    "Jílové u Prahy", "Jindřichův Hradec", "Jirkov", "Jiříkov", "Kadaň",
    "Kamenice nad Lipou", "Kamenický Šenov", "Kaplice", "Kardašova Řečice",
    "Karlovy Vary", "Karolinka", "Karviná", "Kasejovice", "Kašperské Hory",
    "Kdyně", "Kelč", "Kladno", "Klášterec nad Ohří", "Klatovy", "Klecany",
    "Klimkovice", "Klobouky u Brna", "Kněževes", "Knín", "Kojetín", "Kolín",
    "Konice", "Kopidlno", "Kopřivnice", "Koryčany", "Kosmonosy", "Kostelec",
    "Kostelec nad Černými lesy", "Kostelec nad Labem", "Kostelec nad Orlicí",
    "Kostelec na Hané", "Košťany", "Kouřim", "Kralovice", "Kralupy nad Vltavou",
    "Krásná Hora nad Vltavou", "Krásná Lípa", "Krásné Údolí", "Krásno",
    "Kravaře", "Kroměříž", "Krupka", "Kryry", "Ktiš", "Kuchyňka", "Kunovice",
    "Kunštát", "Kuřim", "Kynšperk nad Ohří", "Kyjov", "Lanškroun", "Lanžhot",
    "Lázně Bělohrad", "Lázně Bohdaneč", "Lázně Kynžvart", "Lázně Libverda",
    "Ledeč nad Sázavou", "Ledenice", "Lednice", "Lipník nad Bečvou",
    "Lipno nad Vltavou", "Líbeznice",
    "Libčice nad Vltavou", "Liběchov", "Liberec", "Libochovice",
    "Lipník nad Bečvou", "Litomyšl", "Litoměřice",
    "Litvínov", "Lom", "Lomnice nad Lužnicí", "Lomnice nad Popelkou",
    "Lovosice", "Loučná nad Desnou", "Louka",
    "Louny", "Lučina", "Lužec nad Vltavou", "Lysá nad Labem", "Mělník",
    "Městec Králové", "Město Albrechtice",
    "Meziboří", "Meziměstí", "Mikulášovice", "Mikulov", "Milovice", "Mimoň",
    "Miroslav", "Mirotice", "Mirovice",
    "Mladá Boleslav", "Mladé Buky", "Mnichovo Hradiště", "Mníšek pod Brdy",
    "Modřice", "Moravská Třebová",
    "Moravské Budějovice", "Moravský Beroun", "Moravský Krumlov", "Most",
    "Napajedla", "Náchod", "Náměšť nad Oslavou",
    "Náměšť na Hané", "Neratovice", "Netolice", "Neveklov", "Nová Bystřice",
    "Nová Paka", "Nová Role", "Nové Město na Moravě",
    "Nové Město nad Metují", "Nové Město pod Smrkem", "Nový Bor", "Nový Bydžov",
    "Nový Jičín", "Nový Knín",
    "Nymburk", "Odry", "Olomouc", "Opava", "Orlová", "Osek", "Oslavany",
    "Ostrov", "Ostrava", "Pacov", "Pardubice",
    "Pelhřimov", "Písek", "Planá", "Planá nad Lužnicí", "Plasy", "Plzeň",
    "Podbořany", "Poděbrady", "Pohořelice",
    "Police nad Metují", "Polička", "Prachatice", "Praha", "Prostějov",
    "Přelouč", "Přerov", "Příbram",
    "Radnice", "Rakovník", "Rokycany", "Roudnice nad Labem", "Rousínov",
    "Rožmitál pod Třemšínem", "Rožnov pod Radhoštěm",
    "Rumburk", "Rychnov nad Kněžnou", "Rychvald", "Rýmařov", "Sadská",
    "Sedlčany", "Semily", "Slušovice", "Slaný",
    "Sokolov", "Sobotka", "Sobotín", "Staré Město", "Starý Plzenec", "Stochov",
    "Strakonice", "Stráž pod Ralskem",
    "Strážnice", "Stříbro", "Studénka", "Šenov", "Šumperk", "Štětí",
    "Štramberk", "Šumperk", "Tábor", "Tanvald",
    "Teplice", "Terezín", "Tišnov", "Tovačov", "Trhové Sviny", "Trmice",
    "Třebíč", "Třeboň", "Třinec", "Turnov",
    "Uherské Hradiště", "Uherský Brod", "Unhošť", "Úpice", "Ústí nad Labem",
    "Ústí nad Orlicí", "Valašské Klobouky",
    "Valašské Meziříčí", "Vamberk", "Varnsdorf", "Veselí nad Lužnicí",
    "Veselí nad Moravou", "Vidnava", "Vimperk",
    "Vítkov", "Vizovice", "Vodňany", "Volary", "Votice", "Vrchlabí", "Vsetín",
    "Vyškov", "Zábřeh", "Zákupy",
    "Zbiroh", "Zdice", "Zlaté Hory", "Zlín", "Znojmo", "Žamberk", "Žatec",
    "Žďár nad Sázavou", "Železná Ruda", "Železný Brod",
]

let photoCategories = [
    "Portrét", "Svatba", "Rodina", "Miminka & těhotenství", "Móda", "Street",
    "Dokumentární", "Lifestyle", "Glamour", "Boudoir", "Akt",
    "Produkt", "Reklamní", "Jídlo", "Interiér", "Architektura", "Firemní",
    "Event", "Koncertní", "Editorial", "E-commerce",
    "Krajina", "Cestování", "Příroda", "Makro", "Astrofotografie", "Podvodní",
    "Drone", "Ekologická", "Geografická",
    "Sport", "Akční", "Extrémní sporty", "Motorsport", "Zvířata v pohybu",
    "Bojové sporty", "Fine Art", "Black & White", "Analog", "Infrared", "Surrealistická",
    "Minimalistická", "Abstraktní", "Konceptuální", "Street Art", "Kinetická",
    "HDR", "Long Exposure", "Double Exposure", "Digitální manipulace",
    "Kompozitní", "AI generovaná",
    "Historická", "Forenzní", "Letecká", "Válečná", "Novinářská",
    "Mikrofotografie",
]
