//
//  Localization.swift
//  fotofolio2pto
//
//  Created by Kryštof Příhoda on 03.03.2025.
//

public struct L {
    public enum General {
        public static let somethingWentWrong = "Něco se pokazilo."
        public static let pleaseTryAgain = "Zkuste to prosím znovu."
        public static let somethingWentWrongFull = "\(somethingWentWrong) + \(pleaseTryAgain)"
        public static let back = "Zpět"
        public static let cancel = "Zrušit"
    }
    
    public enum Onboarding {
        public static let username = "Uživatelské jméno"
        public static let usernameEng = "Username"
        public static let name = "Jméno a příjmení"
        public static let email = "Email"
        public static let password = "Heslo"
        public static let confirmPassword = "Potvrzení hesla"
        public static let signIn = "Přihlášení."
        public static let signInAction = "Přihlásit se"
        public static let invalidEmailFormat = "Neplatný formát emailové adresy!"
        public static let emailAddressTaken = "Emailová adresa už je registrována!"
        public static let usernameTaken = "Uživatelské jméno už je registrováno!"
        public static let supportedUsernameChars = "Podporované znaky: a-z 0-9 _ ."
        public static let invalidPasswordFormat = "Neplatný formát hesla!"
        public static let passwordMismatch = "Zadaná hesla se neshodují."
        public static let goBackToSignIn = "Zpět na přihlášení"
        public static let next = "Další"
        public static let register = "Registrace."
        public static let finalizeRegistration = "Registrovat"
        public static let passwordRequirements = "Heslo musí mít více než 8 znaků, obsahovat aspoň 1 velké písmeno, 3 číslice a 1 speciální znak: !@#$%^&*_+:.?"
        public static let tryAgain = "Zkusit znovu"
        public static let profileType = "Typ profilu"
        public static let typeCreator = "Tvůrce 📸"
        public static let typeCustomer = "Zákazník"
        public static let becomeACreator = "Staň se tvůrcem! 📸"
        public static let skyIsTheLimit = "Sky is the limit! 🌟"
        public static let creatorDescription = "Tvůrci mohou vytvářet portfolia a prezentovat svou práci."
        public static let yearsOfExperience = "Roky zkušeností ve fotografii"
        public static let wrongCredentials = "Špatné přihlašovací údaje."
    }
    
    public enum Feed {
        public static let title = "Feed"
        public static let noFilterResults = "Filtrování neodpovídá žádný výsledek."
        public static let sort = "Seřadit"
        public static let sortByDate = "Podle data"
        public static let sortByRating = "Podle hodnocení"
        public static let filter = "Filtrovat"
        public static let filterPortfolios = "Filtrovat portfolia"
        public static let weddingExample = "např. svatba"
        public static let add = "Přidat"
        public static let portfolioAdded = "Portfolio přidáno do výběru."
        public static let portfolioRemoved = "Portfolio odstraněno z výběru."
        public static let portfolioLoadFailed = "Načítání portfolií selhalo, zkuste to prosím znovu."
        public static let profileLoadFailed = "Načítání profilu selhalo, zkuste to prosím znovu."
    }
    
    public enum Selection {
        public static let title = "Výběr"
        public static let emptySelection = "Ve svém výběru nemáte žádná portfolia."
        public static let removeAll = "Odstranit vše"
        public static let remove = "Odstranit"
        public static let typeMessage = "Napsat zprávu"
        public static let noRating = "Bez hodnocení"
        public static let profileDescriptionError = "Profilový popis se nepodařilo nahrát, zkuste to znovu."
        public static let removeAllFromSelection = "Odstranit všechna portfolia z výběru?"
        public static let removePortfolioFromSelection = "Odstranit portfolio z výběru?"
        public static let portfolioRemoved = "Portfolio odstraněno z výběru."
        public static let removedAll = "Všechna portfolia byla odstraněna z vašeho výběru."
        public static let username = "username"
        public static let fullName = "Jméno Příjmení"
        public static let location = "Lokace"
        public static let profileText = "Profilový popis"
        public static let profileLoadFailed = "Načítání profilu selhalo, zkuste to prosím znovu."
        public static let portfolioLoadFailed = "Načítání portfolií selhalo, zkuste to prosím znovu."
        public static let czk = " Kč"
    }
    
    public enum Search {
        public static let title = "Vyhledávání uživatelů"
        public static let tabTitle = "Vyhledávání"
        public static let search = "Hledat"
    }
    
    public enum Messages {
        public static let title = "Zprávy"
        public static let noMessages = "Žádné zprávy."
        public static let youFormat = "Vy:"
        public static let search = "Hledat"
        public static let newChat = "Nový chat"
        public static let send = "Odeslat"
        public static let prefill = "..."
        public static let chatTitle = "Chat"
        public static let sender = "Odesílatel"
        public static let someone = "Uživatel"
        public static let loadFailed = "Načítání zpráv selhalo, zkuste to znovu."
        public static let sendFailed = "Odeslání selhalo, zkuste to znovu."
    }
    
    public enum Profile {
        public static let title = "Profil"
        public static let settings = "Nastavení"
        public static let general = "Obecné"
        public static let about = "O aplikaci"
        public static let editProfile = "Upravit profil"
        public static let editPortfolios = "Upravit portfolia"
        public static let signOut = "Odhlásit se"
        public static let editTitle = "Úprava profilu"
        public static let save = "Uložit"
        public static let yesCancel = "Ano, zahodit změny"
        public static let yesRemove = "Ano, smazat"
        public static let weddingExample = "např. svatba"
        public static let portraitsExample = "např. Portrét"
        public static let add = "Přidat"
        public static let yearsOfExperience = "Počet let zkušeností"
        public static let yearsOfExperiencePrefill = "3"
        public static let description = "Profilový popis"
        public static let activePlace = "Místo působení"
        public static let usernameError = "Uživatelské jméno se nepodařilo načíst..."
        public static let nameError = "Jméno se nepodařilo načíst..."
        public static let titleName = "Název"
        public static let photography = "Fotografie"
        public static let shortDescription = "Popis"
        public static let maxNumberOfTags = "Kategorie (1 až 5)"
        public static let createNew = "Vytvořit"
        public static let newPortfolioTitle = "Nové portfolio"
        public static let portfolios = "Portfolia"
        public static let goBack = "Opravdu chcete zahodit provedené změny?"
        public static let deletePortfolio = "Opravdu chcete portfolio smazat? Tato akce je nevratná."
        public static let userNotACreator = "Uživatel není tvůrce."
        public static let noPortfoliosToShow = "Žádná portfolia k zobrazení."
        public static let noPortfoliosUploaded = "Uživatel zatím nenahrál žádná portfolia."
        public static let rating = "Hodnocení"
        public static let noRating = "Zatím bez hodnocení."
        public static let giveRating = "Udělit hodnocení"
        public static let singleYearExperience = " rok fotografem"
        public static let lessThanFiveExperience = " roky fotografem"
        public static let moreThanFiveExperience = " let fotografem"
        public static let outOf5 = " z 5"
        public static let portfolioCreationFailed = "Vytvoření nového portfolia selhalo, zkuste to prosím znovu."
        public static let portfolioUpdateFailed = "Aktualizace portfolia selhala, zkuste to prosím znovu."
        public static let portfolioDeleteFailed = "Aktualizace portfolia selhala, zkuste to prosím znovu."
        public static let profileLoadFailed = "Načítání profilu selhalo, zkuste to prosím znovu."
        public static let profileUpdateFailed = "Aktualizace profilu selhala, zkuste to prosím znovu."
        public static let profilePicUpdateFailed = "Aktualizace profilové fotky selhala, zkuste to prosím znovu."
        public static let price = "Cena"
        public static let priceInCZK = "Cena (Kč)"
        public static let priceOnRequest = "Cena dohodou"
        public static let priceFixed = "Fixní"
        public static let notIntegerError = "Špatný vstup, zadejte číselnou hodnotu bez mezer."
        public static let maxCategoriesWarning = "Vybral/a jste maximální počet kategorií."
    }
}
