name: Ktor Repository Unit Tests

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./server/gradlew

      - name: Run tests
        run: ./server/gradlew test
